version: "3.9"
services:
  api:
    container_name: jakob-srumpf-courses
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      STAGE: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres 
      DATABASE_PWD: postgres
      DATABASE_NAME: jakob-srumpf-courses-db
      JWT_SECRET: cc302ab976ccb5bd504941997cb04a19a8ebe8c45c2d599ac8a889a030e73b9e
      JWT_SECRET_EXPIRES: 900
      JWT_REFRESH_SECRET: da84ea534ccf42694144334c8f5da683106bfbd6189c932e7ebbc0ffc746147e
      JWT_REFRESH_SECRET_EXPIRES: 122400
      PORT: 8080
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jakob-srumpf-courses-db



